# Site settings
title: Mike Miller's Development Ramblings
email: mmilleruva@gmail.com
description: "A place for me to help remember what I have been working on"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: mmilleruva
github_username:  mmilleruva

# Build settings
markdown: kramdown
permalink: pretty
