# Site settings
title: Seeing The Light
email: mmilleruva@gmail.com
description: "A blog about getting up to speed on modern development"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: mmilleruva
github_username:  mmilleruva

# Build settings
markdown: kramdown
permalink: pretty
