# Site settings
title: MMillerUVA
email: mmilleruva@gmail.com
description: "Mike Miller's blog about development"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  mmilleruva

# Build settings
markdown: kramdown
permalink: pretty
